services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    container_name: mongo2
    networks:
      - recruit2-network
    ports:
      - 27017:27017

networks:
  recruit2-network:
    driver: bridge
