using Esfa.Recruit.Shared.Web.Helpers;
using Esfa.Recruit.Vacancies.Client.Domain.Entities;
using FluentAssertions;
using Xunit;

namespace Esfa.Recruit.Vacancies.Client.UnitTests.Shared.Web.Helpers
{
    public class VacancyFilterHeadingHelperTests
    {
        [Theory]
        [InlineData("advert", 0, FilteringOptions.All, "", "0 adverts")]
        [InlineData("advert", 0, FilteringOptions.Live, "", "0 live adverts")]
        [InlineData("advert", 0, FilteringOptions.Referred, "", "0 rejected adverts")]
        [InlineData("advert", 0, FilteringOptions.Submitted, "", "0 adverts pending dfe review")]
        [InlineData("advert", 0, FilteringOptions.Review, "", "0 adverts pending employer review")]
        [InlineData("advert", 0, FilteringOptions.Draft, "", "0 draft adverts")]
        [InlineData("advert", 0, FilteringOptions.Closed, "", "0 closed adverts")]
        [InlineData("advert", 1, FilteringOptions.All, "", "1 advert")]
        [InlineData("advert", 1, FilteringOptions.Live, "", "1 live advert")]
        [InlineData("advert", 1, FilteringOptions.Referred, "", "1 rejected advert")]
        [InlineData("advert", 1, FilteringOptions.Submitted, "", "1 advert pending dfe review")]
        [InlineData("advert", 1, FilteringOptions.Review, "", "1 advert pending employer review")]
        [InlineData("advert", 1, FilteringOptions.Draft, "", "1 draft advert")]
        [InlineData("advert", 1, FilteringOptions.Closed, "", "1 closed advert")]
        [InlineData("advert", 6, FilteringOptions.All, "", "6 adverts")]
        [InlineData("advert", 6, FilteringOptions.Live, "", "6 live adverts")]
        [InlineData("advert", 6, FilteringOptions.Referred, "", "6 rejected adverts")]
        [InlineData("advert", 6, FilteringOptions.Submitted, "", "6 adverts pending dfe review")]
        [InlineData("advert", 6, FilteringOptions.Review, "", "6 adverts pending employer review")]
        [InlineData("advert", 6, FilteringOptions.Draft, "", "6 draft adverts")]
        [InlineData("advert", 6, FilteringOptions.Closed, "", "6 closed adverts")]
        [InlineData("advert", 0, FilteringOptions.NewApplications, "", "0 adverts with new applications")]
        [InlineData("advert", 0, FilteringOptions.AllApplications, "", "0 adverts with applications")]
        [InlineData("advert", 0, FilteringOptions.ClosingSoonWithNoApplications, "", "0 adverts closing soon without applications")]
        [InlineData("advert", 0, FilteringOptions.ClosingSoon, "", "0 adverts closing soon")]
        [InlineData("advert", 0, FilteringOptions.Transferred, "", "0 adverts transferred from provider")]
        [InlineData("advert", 1, FilteringOptions.NewApplications, "", "1 advert with new applications")]
        [InlineData("advert", 1, FilteringOptions.AllApplications, "", "1 advert with applications")]
        [InlineData("advert", 1, FilteringOptions.ClosingSoonWithNoApplications, "", "1 advert closing soon without applications")]
        [InlineData("advert", 1, FilteringOptions.ClosingSoon, "", "1 advert closing soon")]
        [InlineData("advert", 1, FilteringOptions.Transferred, "", "1 advert transferred from provider")]
        [InlineData("advert", 6, FilteringOptions.NewApplications, "", "6 adverts with new applications")]
        [InlineData("advert", 6, FilteringOptions.AllApplications, "", "6 adverts with applications")]
        [InlineData("advert", 6, FilteringOptions.ClosingSoonWithNoApplications, "", "6 adverts closing soon without applications")]
        [InlineData("advert", 6, FilteringOptions.ClosingSoon, "", "6 adverts closing soon")]
        [InlineData("advert", 6, FilteringOptions.Transferred, "", "6 adverts transferred from provider")]
        [InlineData("advert", 0, FilteringOptions.All, "search", "0 adverts with 'search'")]
        [InlineData("advert", 0, FilteringOptions.Live, "search", "0 live adverts with 'search'")]
        [InlineData("advert", 0, FilteringOptions.Referred, "search", "0 rejected adverts with 'search'")]
        [InlineData("advert", 0, FilteringOptions.Submitted, "search", "0 adverts pending dfe review with 'search'")]
        [InlineData("advert", 0, FilteringOptions.Review, "search", "0 adverts pending employer review with 'search'")]
        [InlineData("advert", 0, FilteringOptions.Draft, "search", "0 draft adverts with 'search'")]
        [InlineData("advert", 0, FilteringOptions.Closed, "search", "0 closed adverts with 'search'")]
        [InlineData("advert", 1, FilteringOptions.All, "search", "1 advert with 'search'")]
        [InlineData("advert", 1, FilteringOptions.Live, "search", "1 live advert with 'search'")]
        [InlineData("advert", 1, FilteringOptions.Referred, "search", "1 rejected advert with 'search'")]
        [InlineData("advert", 1, FilteringOptions.Submitted, "search", "1 advert pending dfe review with 'search'")]
        [InlineData("advert", 1, FilteringOptions.Review, "search", "1 advert pending employer review with 'search'")]
        [InlineData("advert", 1, FilteringOptions.Draft, "search", "1 draft advert with 'search'")]
        [InlineData("advert", 1, FilteringOptions.Closed, "search", "1 closed advert with 'search'")]
        [InlineData("advert", 6, FilteringOptions.All, "search", "6 adverts with 'search'")]
        [InlineData("advert", 6, FilteringOptions.Live, "search", "6 live adverts with 'search'")]
        [InlineData("advert", 6, FilteringOptions.Referred, "search", "6 rejected adverts with 'search'")]
        [InlineData("advert", 6, FilteringOptions.Submitted, "search", "6 adverts pending dfe review with 'search'")]
        [InlineData("advert", 6, FilteringOptions.Review, "search", "6 adverts pending employer review with 'search'")]
        [InlineData("advert", 6, FilteringOptions.Draft, "search", "6 draft adverts with 'search'")]
        [InlineData("advert", 6, FilteringOptions.Closed, "search", "6 closed adverts with 'search'")]
        [InlineData("advert", 0, FilteringOptions.NewApplications, "search", "0 adverts with new applications with 'search'")]
        [InlineData("advert", 0, FilteringOptions.AllApplications, "search", "0 adverts with applications with 'search'")]
        [InlineData("advert", 0, FilteringOptions.ClosingSoonWithNoApplications, "search", "0 adverts closing soon without applications with 'search'")]
        [InlineData("advert", 0, FilteringOptions.ClosingSoon, "search", "0 adverts closing soon with 'search'")]
        [InlineData("advert", 0, FilteringOptions.Transferred, "search", "0 adverts transferred from provider with 'search'")]
        [InlineData("advert", 1, FilteringOptions.NewApplications, "search", "1 advert with new applications with 'search'")]
        [InlineData("advert", 1, FilteringOptions.AllApplications, "search", "1 advert with applications with 'search'")]
        [InlineData("advert", 1, FilteringOptions.ClosingSoonWithNoApplications, "search", "1 advert closing soon without applications with 'search'")]
        [InlineData("advert", 1, FilteringOptions.ClosingSoon, "search", "1 advert closing soon with 'search'")]
        [InlineData("advert", 1, FilteringOptions.Transferred, "search", "1 advert transferred from provider with 'search'")]
        [InlineData("advert", 6, FilteringOptions.NewApplications, "search", "6 adverts with new applications with 'search'")]
        [InlineData("advert", 6, FilteringOptions.AllApplications, "search", "6 adverts with applications with 'search'")]
        [InlineData("advert", 6, FilteringOptions.ClosingSoonWithNoApplications, "search", "6 adverts closing soon without applications with 'search'")]
        [InlineData("advert", 6, FilteringOptions.ClosingSoon, "search", "6 adverts closing soon with 'search'")]
        [InlineData("advert", 6, FilteringOptions.Transferred, "search", "6 adverts transferred from provider with 'search'")]
        [InlineData("vacancy", 0, FilteringOptions.All, "", "0 vacancies")]
        [InlineData("vacancy", 0, FilteringOptions.Live, "", "0 live vacancies")]
        [InlineData("vacancy", 0, FilteringOptions.Referred, "", "0 rejected vacancies")]
        [InlineData("vacancy", 0, FilteringOptions.Submitted, "", "0 vacancies pending dfe review")]
        [InlineData("vacancy", 0, FilteringOptions.Review, "", "0 vacancies pending employer review")]
        [InlineData("vacancy", 0, FilteringOptions.Draft, "", "0 draft vacancies")]
        [InlineData("vacancy", 0, FilteringOptions.Closed, "", "0 closed vacancies")]
        [InlineData("vacancy", 1, FilteringOptions.All, "", "1 vacancy")]
        [InlineData("vacancy", 1, FilteringOptions.Live, "", "1 live vacancy")]
        [InlineData("vacancy", 1, FilteringOptions.Referred, "", "1 rejected vacancy")]
        [InlineData("vacancy", 1, FilteringOptions.Submitted, "", "1 vacancy pending dfe review")]
        [InlineData("vacancy", 1, FilteringOptions.Review, "", "1 vacancy pending employer review")]
        [InlineData("vacancy", 1, FilteringOptions.Draft, "", "1 draft vacancy")]
        [InlineData("vacancy", 1, FilteringOptions.Closed, "", "1 closed vacancy")]
        [InlineData("vacancy", 6, FilteringOptions.All, "", "6 vacancies")]
        [InlineData("vacancy", 6, FilteringOptions.Live, "", "6 live vacancies")]
        [InlineData("vacancy", 6, FilteringOptions.Referred, "", "6 rejected vacancies")]
        [InlineData("vacancy", 6, FilteringOptions.Submitted, "", "6 vacancies pending dfe review")]
        [InlineData("vacancy", 6, FilteringOptions.Review, "", "6 vacancies pending employer review")]
        [InlineData("vacancy", 6, FilteringOptions.Draft, "", "6 draft vacancies")]
        [InlineData("vacancy", 6, FilteringOptions.Closed, "", "6 closed vacancies")]
        [InlineData("vacancy", 0, FilteringOptions.NewApplications, "", "0 vacancies with new applications")]
        [InlineData("vacancy", 0, FilteringOptions.AllApplications, "", "0 vacancies with applications")]
        [InlineData("vacancy", 0, FilteringOptions.ClosingSoonWithNoApplications, "", "0 vacancies closing soon without applications")]
        [InlineData("vacancy", 0, FilteringOptions.ClosingSoon, "", "0 vacancies closing soon")]
        [InlineData("vacancy", 0, FilteringOptions.Transferred, "", "0 vacancies transferred from provider")]
        [InlineData("vacancy", 1, FilteringOptions.NewApplications, "", "1 vacancy with new applications")]
        [InlineData("vacancy", 1, FilteringOptions.AllApplications, "", "1 vacancy with applications")]
        [InlineData("vacancy", 1, FilteringOptions.ClosingSoonWithNoApplications, "", "1 vacancy closing soon without applications")]
        [InlineData("vacancy", 1, FilteringOptions.ClosingSoon, "", "1 vacancy closing soon")]
        [InlineData("vacancy", 1, FilteringOptions.Transferred, "", "1 vacancy transferred from provider")]
        [InlineData("vacancy", 6, FilteringOptions.NewApplications, "", "6 vacancies with new applications")]
        [InlineData("vacancy", 6, FilteringOptions.AllApplications, "", "6 vacancies with applications")]
        [InlineData("vacancy", 6, FilteringOptions.ClosingSoonWithNoApplications, "", "6 vacancies closing soon without applications")]
        [InlineData("vacancy", 6, FilteringOptions.ClosingSoon, "", "6 vacancies closing soon")]
        [InlineData("vacancy", 6, FilteringOptions.Transferred, "", "6 vacancies transferred from provider")]
        [InlineData("vacancy", 0, FilteringOptions.All, "search", "0 vacancies with 'search'")]
        [InlineData("vacancy", 0, FilteringOptions.Live, "search", "0 live vacancies with 'search'")]
        [InlineData("vacancy", 0, FilteringOptions.Referred, "search", "0 rejected vacancies with 'search'")]
        [InlineData("vacancy", 0, FilteringOptions.Submitted, "search", "0 vacancies pending dfe review with 'search'")]
        [InlineData("vacancy", 0, FilteringOptions.Review, "search", "0 vacancies pending employer review with 'search'")]
        [InlineData("vacancy", 0, FilteringOptions.Draft, "search", "0 draft vacancies with 'search'")]
        [InlineData("vacancy", 0, FilteringOptions.Closed, "search", "0 closed vacancies with 'search'")]
        [InlineData("vacancy", 1, FilteringOptions.All, "search", "1 vacancy with 'search'")]
        [InlineData("vacancy", 1, FilteringOptions.Live, "search", "1 live vacancy with 'search'")]
        [InlineData("vacancy", 1, FilteringOptions.Referred, "search", "1 rejected vacancy with 'search'")]
        [InlineData("vacancy", 1, FilteringOptions.Submitted, "search", "1 vacancy pending dfe review with 'search'")]
        [InlineData("vacancy", 1, FilteringOptions.Review, "search", "1 vacancy pending employer review with 'search'")]
        [InlineData("vacancy", 1, FilteringOptions.Draft, "search", "1 draft vacancy with 'search'")]
        [InlineData("vacancy", 1, FilteringOptions.Closed, "search", "1 closed vacancy with 'search'")]
        [InlineData("vacancy", 6, FilteringOptions.All, "search", "6 vacancies with 'search'")]
        [InlineData("vacancy", 6, FilteringOptions.Live, "search", "6 live vacancies with 'search'")]
        [InlineData("vacancy", 6, FilteringOptions.Referred, "search", "6 rejected vacancies with 'search'")]
        [InlineData("vacancy", 6, FilteringOptions.Submitted, "search", "6 vacancies pending dfe review with 'search'")]
        [InlineData("vacancy", 6, FilteringOptions.Review, "search", "6 vacancies pending employer review with 'search'")]
        [InlineData("vacancy", 6, FilteringOptions.Draft, "search", "6 draft vacancies with 'search'")]
        [InlineData("vacancy", 6, FilteringOptions.Closed, "search", "6 closed vacancies with 'search'")]
        [InlineData("vacancy", 0, FilteringOptions.NewApplications, "search", "0 vacancies with new applications with 'search'")]
        [InlineData("vacancy", 0, FilteringOptions.AllApplications, "search", "0 vacancies with applications with 'search'")]
        [InlineData("vacancy", 0, FilteringOptions.ClosingSoonWithNoApplications, "search", "0 vacancies closing soon without applications with 'search'")]
        [InlineData("vacancy", 0, FilteringOptions.ClosingSoon, "search", "0 vacancies closing soon with 'search'")]
        [InlineData("vacancy", 0, FilteringOptions.Transferred, "search", "0 vacancies transferred from provider with 'search'")]
        [InlineData("vacancy", 1, FilteringOptions.NewApplications, "search", "1 vacancy with new applications with 'search'")]
        [InlineData("vacancy", 1, FilteringOptions.AllApplications, "search", "1 vacancy with applications with 'search'")]
        [InlineData("vacancy", 1, FilteringOptions.ClosingSoonWithNoApplications, "search", "1 vacancy closing soon without applications with 'search'")]
        [InlineData("vacancy", 1, FilteringOptions.ClosingSoon, "search", "1 vacancy closing soon with 'search'")]
        [InlineData("vacancy", 1, FilteringOptions.Transferred, "search", "1 vacancy transferred from provider with 'search'")]
        [InlineData("vacancy", 6, FilteringOptions.NewApplications, "search", "6 vacancies with new applications with 'search'")]
        [InlineData("vacancy", 6, FilteringOptions.AllApplications, "search", "6 vacancies with applications with 'search'")]
        [InlineData("vacancy", 6, FilteringOptions.ClosingSoonWithNoApplications, "search", "6 vacancies closing soon without applications with 'search'")]
        [InlineData("vacancy", 6, FilteringOptions.ClosingSoon, "search", "6 vacancies closing soon with 'search'")]
        [InlineData("vacancy", 6, FilteringOptions.Transferred, "search", "6 vacancies transferred from provider with 'search'")]

        public void GetFilterHeading_ShouldBeExpected(string vacancyTerm, int totalVacancies, FilteringOptions filteringOption, string searchTerm, string expectedResult)
        {
            var actualResult = VacancyFilterHeadingHelper.GetFilterHeading(vacancyTerm, totalVacancies, filteringOption, searchTerm);
                
            actualResult.Should().Be(expectedResult);
        }
    }
}
