
jobs:
- job: CodeBuild
  pool:
    name: DAS - Continuous Integration Agents
  variables:
  - group: BUILD Management Resources
  workspace:
    clean: all
  steps:
  - template: azure-pipelines-templates/build/step/app-build.yml@das-platform-building-blocks
    parameters:
      SonarCloudProjectKey: SkillsFundingAgency_das-recruit
      ContinueOnVulnerablePackageScanError: true

  - task: DotNetCoreCLI@2
    displayName: Publish Web/Api/Job Apps
    inputs:
      command: publish
      publishWebProjects: false
      projects: |
        **/*.@(Web|Api|Jobs).csproj
        !**/*.Shared.Web.csproj
      arguments: -o $(build.artifactstagingdirectory)/publish -c release --no-build

  - task: CopyFiles@2
    displayName: Copy Files to $(build.artifactstagingdirectory)/publish
    inputs:
      Contents: |
        azure/**
      TargetFolder: $(build.artifactstagingdirectory)/publish
      OverWrite: true

  - task: PublishPipelineArtifact@1
    displayName: Publish Artifact - Recruit
    inputs:
      targetPath: $(build.artifactstagingdirectory)/publish
      artifactName: Recruit
